FROM openjdk:8
EXPOSE 8080
ADD ./my-app/target/my-app-1.0-SNAPSHOT.jar  my-app-1.0-SNAPSHOT.jar 
RUN mv my-app-1.0-SNAPSHOT.jar myjenkins.jar
ENTRYPOINT ["java", "-cp","myjenkins.jar","com.mycompany.app.App"]